import os
import json
import logging
import threading
from http.server import HTTPServer, BaseHTTPRequestHandler
from io import BytesIO
from PIL import Image
from google import genai
from google.genai import types
from telegram import Update
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    MessageHandler,
    ContextTypes,
    filters,
)

# 1. Logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# 2. Environment Variables
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not TELEGRAM_BOT_TOKEN or not GEMINI_API_KEY:
    raise ValueError("TELEGRAM_BOT_TOKEN or GEMINI_API_KEY missing!")

ai_client = genai.Client(api_key=GEMINI_API_KEY)

# 3. Simple Built-in Web Server for Render Free Tier (No external library needed)
class SimpleHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"Bot is healthy and running!")

def run_health_server():
    port = int(os.environ.get("PORT", 8080))
    server = HTTPServer(("0.0.0.0", port), SimpleHandler)
    logger.info(f"Health server running on port {port}")
    server.serve_forever()

# 4. AI Prompt Template
PROMPT_TEXT = """
Read the provided content and create exactly 1 Multiple Choice Question (MCQ).
Return ONLY a valid JSON object (no markdown formatting, no code blocks):
{
  "question": "Question text (max 250 chars)",
  "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
  "correct_option_id": 0,
  "explanation": "Short explanation (max 150 chars)"
}
Rules:
- options must have exactly 4 items, each under 90 characters.
- correct_option_id must be 0, 1, 2, or 3.
- Use the same language as the input text/image.
"""

async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("👋 नमस्ते! मुझे कोई भी फोटो या टेक्स्ट भेजें, मैं तुरंत उसका Quiz Poll बना दूंगा।")

async def process_quiz(update: Update, context: ContextTypes.DEFAULT_TYPE, contents, status_msg):
    try:
        # Naya code (ise daal do)
            contents=contents,
            config=types.GenerateContentConfig(
                response_mime_type="application/json"
            )
        )

        raw_text = response.text.strip()
        if raw_text.startswith("```"):
            raw_text = raw_text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

        quiz_data = json.loads(raw_text)

        question = str(quiz_data.get("question", "")).strip()[:290]
        options = [str(opt).strip()[:95] for opt in quiz_data.get("options", [])][:4]
        correct_id = int(quiz_data.get("correct_option_id", 0))
        explanation = str(quiz_data.get("explanation", "")).strip()[:190]

        if len(options) < 2:
            raise ValueError("Invalid options generated by AI.")

        if correct_id < 0 or correct_id >= len(options):
            correct_id = 0

        await context.bot.send_poll(
            chat_id=update.effective_chat.id,
            question=question,
            options=options,
            type="quiz",
            correct_option_id=correct_id,
            explanation=explanation if explanation else None,
            is_anonymous=False
        )
        await status_msg.delete()

    except Exception as err:
        logger.error(f"Error: {err}")
        await status_msg.edit_text(f"⚠️ Error: {str(err)[:120]}")

async def handle_photo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    status_msg = await update.message.reply_text("📥 फोटो प्रोसेस हो रही है...")
    try:
        photo_file = await update.message.photo[-1].get_file()
        image_bytes = BytesIO()
        await photo_file.download_to_memory(image_bytes)
        image_bytes.seek(0)
        img = Image.open(image_bytes)

        await process_quiz(update, context, [img, PROMPT_TEXT], status_msg)
    except Exception as e:
        logger.error(f"Download error: {e}")
        await status_msg.edit_text(f"⚠️ Photo error: {str(e)[:100]}")

async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.message.text.startswith("/"):
        return
    status_msg = await update.message.reply_text("📝 टेक्स्ट प्रोसेस हो रहा है...")
    await process_quiz(update, context, [update.message.text, PROMPT_TEXT], status_msg)

def main():
    # Start the dummy health check server on a background thread for Render
    server_thread = threading.Thread(target=run_health_server, daemon=True)
    server_thread.start()

    # Start Telegram Bot
    bot_app = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()
    bot_app.add_handler(CommandHandler("start", start_command))
    bot_app.add_handler(MessageHandler(filters.PHOTO, handle_photo))
    bot_app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text))

    logger.info("Bot is running...")
    bot_app.run_polling()

if __name__ == "__main__":
    main()
